services:
  - type: web
    name: AchekBot
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~ROYjTxsq"
      - key: DATABASE_URL
        value: "postgresql://whatsapp_rpjx_user:wsr0RswWPIcCm98miwfa8oGqKbOOc7CQ@dpg-d6enkjogjchc739tmrs0-a/whatsapp_rpjx"
      - key: SUDO
        value: "2348096567473" # Put your phone number here (no + sign)
      - key: STICKER_PACKNAME
        value: "Caleb-MD"
